//package lexical.analyze;
//
//public enum Lex implements tData {
//    lexNone,
//    lexName,
//    lexNum,
//    lexMODULE,
//    lexIMPORT,
//    lexBEGIN,
//    lexEND,
//    lexCONST,
//    lexVAR,
//    lexWHILE,
//    lexDO,
//    lexIF,
//    lexTHEN,
//    lexELSIF,
//    lexELSE,
//    lexMult,
//    lexDIV,
//    lexMOD,
//    lexPlus,
//    lexMinus,
//    lexEQ,
//    lexNE,
//    lexLT,
//    lexLE,
//    lexGT,
//    lexGE,
//    lexDot,
//    lexComma,
//    lexColon,
//    lexSemi,
//    lexAss,
//    lexLpar,
//    lexRpar,
//    lexEOT
//}
